version: "3"

services:
  golang:
    build:
      context: .
    container_name: ${PROJECT_NAME}
    ports:
      - 8084:8084
    restart: always
    environment:
      - ENV=${ENV}
      - PROJECT_NAME=${PROJECT_NAME}
    working_dir: /go/src/${PROJECT_NAME}
    volumes:
      - .:/go/src/${PROJECT_NAME}
    command: "fresh runner.conf"